/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ArticleDialog: typeof import('./src/components/knowledge/ArticleDialog.vue')['default']
    ArticleList: typeof import('./src/components/knowledge/ArticleList.vue')['default']
    ArticlesList: typeof import('./src/components/knowledge/ArticlesList.vue')['default']
    CategoriesSidebar: typeof import('./src/components/knowledge/CategoriesSidebar.vue')['default']
    CategorySidebar: typeof import('./src/components/knowledge/CategorySidebar.vue')['default']
    ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    Features: typeof import('./src/components/index/Features.vue')['default']
    FeaturesSection: typeof import('./src/components/index/FeaturesSection.vue')['default']
    Filters: typeof import('./src/components/history/Filters.vue')['default']
    FilterSection: typeof import('./src/components/history/FilterSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/index/Hero.vue')['default']
    HeroSection: typeof import('./src/components/index/HeroSection.vue')['default']
    HistoryFilterSection: typeof import('./src/components/history/HistoryFilterSection.vue')['default']
    HistoryHeader: typeof import('./src/components/history/HistoryHeader.vue')['default']
    HistoryRecordListView: typeof import('./src/components/history/HistoryRecordListView.vue')['default']
    HistoryReportDialog: typeof import('./src/components/history/HistoryReportDialog.vue')['default']
    HowItWorks: typeof import('./src/components/index/HowItWorks.vue')['default']
    MessageList: typeof import('./src/components/chat/MessageList.vue')['default']
    MobileCategorySelector: typeof import('./src/components/knowledge/MobileCategorySelector.vue')['default']
    RecordListView: typeof import('./src/components/history/RecordListView.vue')['default']
    Records: typeof import('./src/components/history/Records.vue')['default']
    Report: typeof import('./src/components/history/Report.vue')['default']
    ReportDialog: typeof import('./src/components/history/ReportDialog.vue')['default']
    ResultsSection: typeof import('./src/components/scan/ResultsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/knowledge/Sidebar.vue')['default']
    Stats: typeof import('./src/components/history/Stats.vue')['default']
    StatsSection: typeof import('./src/components/index/StatsSection.vue')['default']
    TagsSection: typeof import('./src/components/knowledge/TagsSection.vue')['default']
    Toolbar: typeof import('./src/components/history/Toolbar.vue')['default']
    UploadSection: typeof import('./src/components/scan/UploadSection.vue')['default']
  }
}
